// Fix: Import types from './types'
import { Category, Service } from './types';

export const CATEGORIES: Category[] = [
  { name: 'TikTok - Views [Refill Button Working] NEW' },
  { name: 'TikTok - Likes' },
  { name: 'TikTok - Followers' },
  { name: 'TikTok - Comments' },
  { name: 'TikTok - Shares' },
];

export const SERVICES: Service[] = [
  {
    id: 8680,
    name: 'TikTok - Video Views',
    details: ['Max Unlimited ~ 5M/Days', 'Instant ~ NO REFILL'],
    rate: 2,
    min: 100,
    max: 50000000,
    category: 'TikTok - Views [Refill Button Working] NEW',
  },
  {
    id: 8681,
    name: 'TikTok - Video Views',
    details: ['Max Unlimited ~ 10M-500M/Days', 'Instant ~ NO REFILL'],
    rate: 2.21,
    min: 100,
    max: 500000000,
    category: 'TikTok - Views [Refill Button Working] NEW',
  },
  {
    id: 8682,
    name: 'TikTok - Video Views',
    details: ['Max Unlimited ~ 10M-500M/Days', 'Instant ~ REFILL 30D'],
    rate: 2.5,
    min: 100,
    max: 500000000,
    category: 'TikTok - Views [Refill Button Working] NEW',
    refill: true,
  },
  {
    id: 8683,
    name: 'TikTok - Video Views',
    details: ['Max Unlimited ~ 10M-500M/Days', 'Instant ~ REFILL 120D'],
    rate: 2.3,
    min: 100,
    max: 500000000,
    category: 'TikTok - Views [Refill Button Working] NEW',
    refill: true,
  },
  {
    id: 8684,
    name: 'TikTok - Video Views',
    details: ['Max Unlimited ~ 10M-500M/Days', 'Instant ~ LifeTime'],
    rate: 2.22,
    min: 100,
    max: 500000000,
    category: 'TikTok - Views [Refill Button Working] NEW',
    refill: true,
  },
  {
    id: 8710,
    name: 'TikTok - Video Views',
    details: ['Max Unlimited ~ 10M-500M/Days', 'Instant ~ LifeTime'],
    rate: 2.34,
    min: 100,
    max: 500000000,
    category: 'TikTok - Views [Refill Button Working] NEW',
    refill: true,
  },
  {
    id: 8713,
    name: 'TikTok Likes ~ Hidden Account',
    details: ['Max 5M ~ 50k/Days', 'Instant ~ NO REFILL'],
    rate: 0.0472,
    min: 50,
    max: 5000000,
    category: 'TikTok - Likes',
  },
  {
    id: 8714,
    name: 'TikTok Likes ~ Hidden Account',
    details: ['Max 5M ~ 50k/Days', 'Instant ~ REFILL 30D'],
    rate: 0.0506,
    min: 50,
    max: 5000000,
    category: 'TikTok - Likes',
    refill: true,
  },
  {
    id: 8715,
    name: 'TikTok Likes ~ Hidden Account',
    details: ['Max 5M ~ 50k/Days', 'Instant ~ REFILL 60D'],
    rate: 0.054,
    min: 50,
    max: 5000000,
    category: 'TikTok - Likes',
    refill: true,
  },
  {
    id: 8716,
    name: 'TikTok Likes ~ Hidden Account',
    details: ['Max 5M ~ 50k/Days', 'Instant ~ REFILL 90D'],
    rate: 0.0578,
    min: 50,
    max: 5000000,
    category: 'TikTok - Likes',
    refill: true,
  },
  {
    id: 8717,
    name: 'TikTok Likes ~ Hidden Account',
    details: ['Max 5M ~ 50k/Days', 'Instant ~ REFILL 365D'],
    rate: 0.0606,
    min: 50,
    max: 5000000,
    category: 'TikTok - Likes',
    refill: true,
  },
  {
    id: 8718,
    name: 'TikTok Likes ~ Hidden Account',
    details: ['Max 5M ~ 50k/Days', 'Instant ~ LifeTime'],
    rate: 0.0642,
    min: 50,
    max: 5000000,
    category: 'TikTok - Likes',
    refill: true,
  },
  {
    id: 8220,
    name: 'TikTok - Followers ~ HQ Profiles',
    details: ['~ Max 5M ~ 50k/days ~ INSTANT', '~ NO REFILL'],
    rate: 180.5,
    min: 50,
    max: 5000000,
    category: 'TikTok - Followers',
  },
  {
    id: 8221,
    name: 'TikTok - Followers ~ HQ Profiles',
    details: ['~ Max 5M ~ 50k/days ~ INSTANT', '~ REFILL 30D'],
    rate: 185.75,
    min: 50,
    max: 5000000,
    category: 'TikTok - Followers',
    refill: true,
  },
  {
    id: 8222,
    name: 'TikTok - Followers ~ HQ Profiles',
    details: ['~ Max 5M ~ 50k/days ~ INSTANT', '~ REFILL 60D'],
    rate: 190.25,
    min: 50,
    max: 5000000,
    category: 'TikTok - Followers',
    refill: true,
  },
  {
    id: 8223,
    name: 'TikTok - Followers ~ HQ Profiles',
    details: ['~ Max 5M ~ 50k/days ~ INSTANT', '~ REFILL 90D'],
    rate: 193.5,
    min: 50,
    max: 5000000,
    category: 'TikTok - Followers',
    refill: true,
  },
  {
    id: 8224,
    name: 'TikTok - Followers ~ HQ Profiles',
    details: ['~ Max 5M ~ 50k/days ~ INSTANT', '~ REFILL 365D'],
    rate: 196.8,
    min: 50,
    max: 5000000,
    category: 'TikTok - Followers',
    refill: true,
  },
  {
    id: 8225,
    name: 'TikTok - Followers ~ HQ Profiles',
    details: ['~ Max 5M ~ 50k/days ~ INSTANT', '~ LifeTime'],
    rate: 199.99,
    min: 50,
    max: 5000000,
    category: 'TikTok - Followers',
    refill: true,
  },
  {
    id: 8121,
    name: 'Tiktok Custom Comments | Max: 10K',
    details: [],
    rate: 0.7904,
    min: 10,
    max: 10000,
    category: 'TikTok - Comments',
  },
  {
    id: 8122,
    name: 'Tiktok Emoji Comments | Max: 10K',
    details: [],
    rate: 0.3367,
    min: 10,
    max: 10000,
    category: 'TikTok - Comments',
  },
  {
    id: 8123,
    name: 'Tiktok Comment Likes | Max: 10K',
    details: [],
    rate: 0.3601,
    min: 10,
    max: 10000,
    category: 'TikTok - Comments',
  },
  {
    id: 8001,
    name: 'TikTok - Shares - Max 100K',
    details: [],
    rate: 0.15,
    min: 100,
    max: 100000,
    category: 'TikTok - Shares',
  },
];
